Repository konveyor/go-konveyor-tests, pull requests merged in 2024-12, with the labels that each got.

#230 Add release-0.6 to workflows
  .github/workflows/releases-tier0.yml
  .github/workflows/releases-tier1.yml
  .github/workflows/releases-tier2.yml
Labels: cherry-pick/release-0.6

#229 [RFR] Analyze Coolstore app off Quarkus branch - Source and dependencies
  analysis/tc_coolstore_deps_quarkus.go
  analysis/test_cases.go
  data/application.go
Labels: cherry-pick/release-0.5, cherry-pick/release-0.6

#233 Use kubectl instead of oc commands
  e2e/metrics/metrics_utils.go
Labels: cherry-pick/release-0.3, cherry-pick/release-0.4, cherry-pick/release-0.5, cherry-pick/release-0.6

#239 Enable uploading custom rules in analysis
  analysis/analysis_test.go
  analysis/data/rules/hz.windup.xml
  analysis/pkg.go
  analysis/tc_petclinic_hazelcast.go
Labels: cherry-pick/release-0.5, cherry-pick/release-0.6
